repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: end-of-file-fixer
      - id: double-quote-string-fixer
      - id: detect-private-key
      # - id: detect-aws-credentials
      - id: trailing-whitespace
      - id: flake8
        args: [--max-line-length=120]
  # - repo: local
  #   hooks:
  #     - id: radon
  #       name: radon
  #       entry: radon cc -a -s -nb hades/
  #       language: python
  #       types: [python]
#  - repo: local
#    hooks:
#      - id: testing
#        name: testing
#        entry: pytest -vvv tests/
#        language: python
#        types: [python]
